### ISSUE TITLE
initial configuration

### ISSUE THREAD

**Issue by wendellmva** [dirtsimple/poste.io#14]
I want to know if there's a way to do the initial setup programmatically instead of doing it through the user interface. The api is very handy but it requires authentication with an admin user. What I am looking for it something like

`docker-compose exec init mail.example.com admin "password"`

Or any other way to fully automate the setup with docker-compose.

**Comment by pjeby** [comment]
If you run `sqlite3 /data/users.db` in the container you can insert a user in the table directly.  You should probably only do that as a temporary hack to get the API up and running, though, since the home directory won't exist.  After you use the API to insert a proper super-admin, you can then delete the dummy user via sqlite3 (since again, the home dir won't exist and deleting via the API might cause issues.

**Comment by pjeby** [comment]
Oh, also, there is a [command-line tool](https://admin%40poste.io:admin@demo.poste.io/admin/api/doc) you can use (scroll to the bottom of that page, click on "show command line API").  Basically, just run `poste` via `exec` and it'll give you commands you can run.  Don't know if they can be run in a completely new server, but if they can, it's better than messing with sqlite directly.

**Comment by wendellmva** [comment]
yup the command line tool worked like a charm 100% automation was achieved
