### ISSUE TITLE
Rotation Output IP

### ISSUE THREAD

**Issue by ooclaar** [dirtsimple/poste.io#19]
Would you know how I could put multiple outgoing IPs so they can rotate between them? Does your solution make it possible to do this?

**Comment by pjeby** [comment]
The outbound IP config file is read for every email sent, so you can rotate that on some time period if you like.  You could also change the [outbound IPs plugin](https://github.com/dirtsimple/poste.io/blob/master/files/opt/haraka-smtp/plugins/outbound_ips.js) in your own derivative image to operate differently.

**Comment by ooclaar** [comment]
Hello, could you help me to build an IP rotation for my server? If possible could you give me your email? I would be happy to negotiate a payment amount.

**Comment by pjeby** [comment]
Please note that I have a $3k USD project minimum -- you may wish to get a cheaper programmer for this task since simply rotating the file with a cron job and shell script is doable for time-based rotation, and if you have something more complex, a JavaScript programmer could create a different version of the outbound IPs plugin.  But if your requirements are more complex and you have the budget, feel free to email sales at dirtsimple.org.
