### ISSUE TITLE
Support ipv6

### ISSUE THREAD

**Issue by SuperSandro2000** [dirtsimple/poste.io#2]

**Comment by pjeby** [comment]
You forgot to include a description of what you want.  In principle, the container should work with IPv6, provided that the container hostname maps in DNS to exactly one IPv6 address, and *no* other addresses (i.e., no IPv4 addresses).  Have you tried that yet?

As far as I can tell, such a configuration should work just fine; I simply haven't tested it, because I don't currently have any use cases for IPv6.

Now, if you want to support using IPv6 and IPv4 *at the same time* then I'm not sure how well that will work with the current codebase.  But in order to proceed any further, I would need for you to actually provide information on what did and did not work with such a scenario.  At this point, it is unclear to me if you have even tried anything at all, let alone what happened when you did.

Anyway, it's generally polite when filing bug reports or feature requests with an open source project to include a detailed description of what you are asking for, including details about what you've tried, what result you got, and what results you were expecting.  Without it, it may be impossible for them to even understand what you're asking for, let alone have any possibility of providing it.

**Comment by pjeby** [comment]
As of d907720cd, I've added support for multiple IP addresses (possibly including IPv6), so be sure to pull the latest image before testing.

All I've done at this point is confirm that all addresses listed in DNS for the hostname are listened to (and no others), and that the first such address is used for outgoing connections, unless overrridden via the `OUTBOUND_MAIL_IP` environment variable.  So you *should* be able to use IPv6, pending testing, but you will still need to choose *one* address (either IPv6 or IPv4, but not both) for outgoing mail to "come from".

**Comment by pjeby** [comment]
The current version supports mixing and matching multiple IPs that can be IPv4 or IPv6.  I haven't tested IPv6 addresses except to confirm that they are listened on, not whether mail can be sent via them.  (Since most mail servers do not support IPv6.)  So I would not recommend trying to set outgoing IPv6 addresses, even if they *might* work in some specific cases.
