### ISSUE TITLE
Download mail from remote IMAP and POP servers

### ISSUE THREAD

**Issue by atsanna** [dirtsimple/poste.io#21]
Can I automatically download mail from remote IMAP and POP servers to save it in local mailboxes, for example using fetchmail?
I think it is a very useful function.
If I have a mail server hosted on a datacenter like OVH, I could download mail to a local server with poste.io and, if the latter goes offline, I would still receive mail on the remote server.
When the local server comes back online, I will be able to download mail from the remote server again.
What do you think?

**Comment by pjeby** [comment]
That certainly sounds like something you could implement if you wanted.  It's not a feature I will be incorporating into this image any time soon, though, as it's not something I need for my business at this time.

Do bear in mind that since this is a Docker image, you can extend on it with your own code, scripts, etc, in the same way as I have extended the original poste.io image to add various features.  You could have an image that adds fetchmail and a cron job and perhaps look for certain config files in the /data volume.

(Also note that you can just use a backup MX service to do all this in the first place, or configure your remote mail server to act as a backup MX for your home server.)
