### ISSUE TITLE
TRUENAS SCALE

### ISSUE THREAD

**Issue by alexbonazzi** [dirtsimple/poste.io#31]
I want to use poste.io on truenas scale. How can I do it ?

**Comment by pjeby** [comment]
I don't know.  This isn't the poste.io official project, this is a variant image for people with different needs than the official image.

If your question is about the official poste.io, go to https://poste.io/ instead.  If you get it working it on wherever you're trying to, and *then* you switch to using this image instead of the official one, *and* there's a problem the official image doesn't have, you can report it here.

**Comment by alexbonazzi** [comment]
Thanks

Il sab 11 mag 2024, 19:29 PJ Eby ***@***.***> ha scritto:
